/// <reference types="@cloudflare/workers-types" />

// Custom Worker entry. Wraps the OpenNext-generated handler with edge-layer
// rate limiting and verified-bot bypass. The OpenNext build emits
// `.open-next/worker.js` (gitignored, regenerated by `opennextjs-cloudflare
// build`) which exports the Next handler + the DOQueueHandler durable object.
// @ts-expect-error — generated at build time; absent during typecheck
import openNextHandler, { DOQueueHandler } from "./.open-next/worker.js";

export { DOQueueHandler };

const VERSION_PATH = /^\/[^/]+\/[^/]+\/v\//;

type RateLimitBinding = { limit: (input: { key: string }) => Promise<{ success: boolean }> };

type Env = {
  RATE_LIMIT_GENERAL?: RateLimitBinding;
  RATE_LIMIT_VERSION?: RateLimitBinding;
};

function tooManyRequests(): Response {
  return new Response("Too many requests. Please try again shortly.", {
    status: 429,
    headers: { "Cache-Control": "no-store" },
  });
}

const wrapped: ExportedHandler<Env> = {
  async fetch(req, env, ctx) {
    const cf = (req as Request & { cf?: { botManagement?: { verifiedBot?: boolean } } }).cf;
    const verifiedBot = cf?.botManagement?.verifiedBot === true;

    if (!verifiedBot && env.RATE_LIMIT_GENERAL) {
      const ip = req.headers.get("CF-Connecting-IP") ?? "anonymous";
      const general = await env.RATE_LIMIT_GENERAL.limit({ key: ip });
      if (!general.success) return tooManyRequests();

      if (env.RATE_LIMIT_VERSION && VERSION_PATH.test(new URL(req.url).pathname)) {
        const version = await env.RATE_LIMIT_VERSION.limit({ key: ip });
        if (!version.success) return tooManyRequests();
      }
    }

    return (openNextHandler as ExportedHandler<Env>).fetch!(req, env, ctx);
  },
};

export default wrapped;
